## This is test deployment for Kubernetes platforms.
## This is not intended to be used in production.
##
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloud-migration-concept-example
  name: cloud-migration-concept-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-migration-concept-example
  template:
    metadata:
      labels:
        app: cloud-migration-concept-example
    spec:
      containers:
      - image: ynahshal/cloud-migration-concept-example:0.0.2
        name: cloud-migration-concept-example
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-migration-concept-example
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: cloud-migration-concept-example
  type: NodePort